### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'dependencies' in ../package.json

### ISSUE THREAD

**Issue by mikedamage** [bumped/bumped#118]
I just updated bumped to 0.10.7 and started getting this error, which appears any time I run the `bumped` executable, regardless of command:

```
TypeError: Cannot use 'in' operator to search for 'dependencies' in ../package.json
    at Object.<anonymous> (/home/mike/development/work/grunt-epublishing/node_modules/normalize-package-data/lib/fixer.js:138:18)
    at Array.forEach (<anonymous>:null:null)
    at Object.fixDependencies (/home/mike/development/work/grunt-epublishing/node_modules/normalize-package-data/lib/fixer.js:137:41)
    at /home/mike/development/work/grunt-epublishing/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>:null:null)
    at normalize (/home/mike/development/work/grunt-epublishing/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at module.exports (/home/mike/development/work/grunt-epublishing/node_modules/bumped/node_modules/meow/index.js:54:2)
    at Object.<anonymous> (/home/mike/development/work/grunt-epublishing/node_modules/bumped/bin/index.js:8:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I've tried reinstalling my Node modules, using a global install vs. local to my project, and the error is the same. The exception appears to come from the `meow` call on line 8 of bin/index.js, passing a literal `"../package.json"` string. Any help would be appreciated - thanks!

**Comment by Kikobeats** [comment]
hum, what command do you do for getting the error?

**Comment by mikedamage** [comment]
It happens for me when I run any bumped command. I first noticed it when trying to run `bumped release patch`, but it also occurs for `bumped help`. The primary way I use bumped is via NPM scripts, so I'm running the executable that's installed in my project's node_modules/.bin directory. I've also tried installing globally, though, and I get the same behavior. I'm on Node v8.9.0, NPM v5.5.1

**Comment by Kikobeats** [comment]
detected and fixed in the last patch!

**Comment by mikedamage** [comment]
Awesome - thank you!!!

**Comment by carlosparreno** [comment]
Hi @Kikobeats , Thanks for fixing this. I'm running into the same problem. Do you know when you will release the next patch release (0.10.8)? I appreciate your effort. Thanks!

**Comment by Kikobeats** [comment]
@mikedamage @cparreno7 

omg I forgot release the patch! Thanks for remembering to me.

I released it right now, can you confirm?

**Comment by carlosparreno** [comment]
Hi @Kikobeats. I confirm that this is fixed, I just tested it.

Thanks buddy!
