### ISSUE TITLE
Error when running with npm-scripts

### ISSUE THREAD

**Issue by 1natsu172** [bumped/bumped#124]
I'm trying to use 'bumped' from npm-scripts in my project, but I get an "npm error".

In this way, commands are defined in npm-scripts. 

**package.json**
```json
"scripts": {
    "bump:major": "bumped release major",
    "bump:minor": "bumped release minor",
    "bump:patch": "bumped release patch",
    "bump:version": "bumped version",
    "bump:init": "bumped init"
}
```

At first, `npm run bump: init` has no problem and` .bumpedrc` is generated.
Next, run `npm run bump: version` then I get an error like this:

**Run `npm run version` then Error!**
```zsh
bumped Current version is 2.5.4.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! repo@2.5.4 bump:version: `bumped version`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the repo@2.5.4 bump:version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2018-02-14T16_25_29_743Z-debug.log
```

**Bumped version check result is appearing properly on line 1 ....**

---

The error log of npm is as follows

```log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/username/.nodebrew/node/v9.5.0/bin/node',
1 verbose cli   '/Users/username/.nodebrew/current/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bump:version' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebump:version', 'bump:version', 'postbump:version' ]
5 info lifecycle repo@2.5.4~prebump:version: repo@2.5.4
6 info lifecycle repo@2.5.4~bump:version: repo@2.5.4
7 verbose lifecycle repo@2.5.4~bump:version: unsafe-perm in lifecycle true
8 verbose lifecycle repo@2.5.4~bump:version: PATH: /Users/username/.nodebrew/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/username/devFolder/test-dev/bumptest/node_modules/.bin:/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/Users/username/.nodebrew/current/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle repo@2.5.4~bump:version: CWD: /Users/username/devFolder/test-dev/bumptest
10 silly lifecycle repo@2.5.4~bump:version: Args: [ '-c', 'bumped version' ]
11 silly lifecycle repo@2.5.4~bump:version: Returned: code: 1  signal: null
12 info lifecycle repo@2.5.4~bump:version: Failed to exec bump:version script
13 verbose stack Error: repo@2.5.4 bump:version: `bumped version`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/username/.nodebrew/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/username/.nodebrew/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid repo@2.5.4
15 verbose cwd /Users/username/devFolder/test-dev/bumptest
16 verbose Darwin 15.6.0
17 verbose argv "/Users/username/.nodebrew/node/v9.5.0/bin/node" "/Users/username/.nodebrew/current/bin/npm" "run" "bump:version"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error repo@2.5.4 bump:version: `bumped version`
22 error Exit status 1
23 error Failed at the repo@2.5.4 bump:version script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

`npm cache clean --force` even if reinstalling node did not recover! Is there any solution? 🙏

**Comment by Kikobeats** [comment]
Thanks for reporting!

If you see the log, the command output the version (`bumped Current version is 2.5.4.`) but npm says command fails.

It was because an internal method for retrieving the version was not passing error as the first argument.

**Comment by Kikobeats** [comment]
Can you confirm v`0.10.9` is working fine?

**Comment by 1natsu172** [comment]
Wow, great work! Thanks for your quick reply and bug fix! 👍 
I tried it with `v0.10.9` and it works fine. The npm error has disappeared. Thanks for offering a nice package 'bumped' 🎉
