### ISSUE TITLE
Bumped doesn't work in official docker node image

### ISSUE THREAD

**Issue by KuSh** [bumped/bumped#189]
```
# bumped release minor

pre bumped Starting Linting config files
pre bumped Finished Linting config files after 50ms.

bumped Releases version 1.1.0.
bumped Plugin bumped-changelog not detected on the system.
bumped Installing it as global, might take a while.
npm ERR! code EXDEV
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! dest /usr/local/lib/node_modules/.npm-i9nnxROI
npm ERR! errno -18
npm ERR! EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm-i9nnxROI'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T14_56_58_737Z-debug.log
node:internal/modules/cjs/loader:922
  throw err;
  ^

Error: Cannot find module '/usr/local/lib/node_modules/bumped-changelog'
Require stack:
- /usr/local/lib/node_modules/bumped/lib/Bumped.plugin.coffee
- /usr/local/lib/node_modules/bumped/lib/Bumped.coffee
- /usr/local/lib/node_modules/bumped/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /usr/local/lib/node_modules/bumped/lib/Bumped.plugin.coffee:82:50
    at replenish (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:440:21)
    at /usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:445:13
    at eachOfLimit$1 (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:471:34)
    at awaitable (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:208:32)
    at Object.eachOfSeries (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:658:16)
    at Object.awaitable (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:208:32)
    at Plugin.exec (/usr/local/lib/node_modules/bumped/lib/Bumped.plugin.coffee:76:20)
    at tasks (/usr/local/lib/node_modules/bumped/lib/Bumped.semver.coffee:105:37)
    at nextTask (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:4576:27)
    at next (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:4584:13)
    at /usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:321:20
    at /usr/local/lib/node_modules/bumped/lib/Bumped.semver.coffee:129:16
    at wrapper (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:268:20)
    at iteratorCallback (/usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:495:17)
    at /usr/local/lib/node_modules/bumped/node_modules/async/dist/async.js:321:20
    at Immediate.<anonymous> (/usr/local/lib/node_modules/bumped/node_modules/nodeify/index.js:15:9)
    at processImmediate (node:internal/timers:463:21)
 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/bumped/lib/Bumped.plugin.coffee',
    '/usr/local/lib/node_modules/bumped/lib/Bumped.coffee',
    '/usr/local/lib/node_modules/bumped/bin/index.js'
  ]
}
```

It seems the culprit is using `cd <globalNpmPath> && npm install <plugin>`instead of `npm install --global <plugin>` in https://github.com/bumped/bumped/blob/4aa483464df1a8d46f904c78f1e0528463b88473/lib/Bumped.plugin.coffee#L15

Installing before hand with npm install --global solves the problem

Regards,
Nicolas

**Comment by Kikobeats** [comment]
Hello and thanks for reporting.

I run bumped normally from my local computer, meaning it was never designed to be run in a CI workflow.

just curious, can you tell me more about your CI workflow?

**Comment by KuSh** [comment]
Hi,

We have a manual job that allow the team to release a new version when needed. I've switched to npm version for now.

Regards
